#############################################################################
# Makefile for building: sourceweb
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ..\sourceweb-master\sourceweb.pro
# Template: subdirs
# Command: C:\Qt\5.8\mingw53_32\bin\qmake.exe -o Makefile ..\sourceweb-master\sourceweb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.8\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-third_party \
		sub-libindexdb \
		sub-clang-indexer \
		sub-index-tool \
		sub-navigator


sub-third_party-qmake_all:  FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
	cd third_party\ && $(MAKE) -f Makefile qmake_all
sub-third_party: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile
sub-third_party-make_first-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-third_party-make_first: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-third_party-all-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-third_party-all: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-third_party-clean-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-third_party-clean: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-third_party-distclean-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-third_party-distclean: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-third_party-install_subtargets-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-third_party-install_subtargets: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-third_party-uninstall_subtargets-ordered: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-third_party-uninstall_subtargets: FORCE
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-libindexdb-qmake_all: sub-third_party-qmake_all FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
	cd libindexdb\ && $(MAKE) -f Makefile qmake_all
sub-libindexdb: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile
sub-libindexdb-make_first-ordered: sub-third_party-make_first-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-libindexdb-make_first: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-libindexdb-all-ordered: sub-third_party-all-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-libindexdb-all: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-libindexdb-clean-ordered: sub-third_party-clean-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-libindexdb-clean: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-libindexdb-distclean-ordered: sub-third_party-distclean-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-libindexdb-distclean: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-libindexdb-install_subtargets-ordered: sub-third_party-install_subtargets-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-libindexdb-install_subtargets: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-libindexdb-uninstall_subtargets-ordered: sub-third_party-uninstall_subtargets-ordered  FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-libindexdb-uninstall_subtargets: FORCE
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-clang-indexer-qmake_all: sub-libindexdb-qmake_all FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
	cd clang-indexer\ && $(MAKE) -f Makefile qmake_all
sub-clang-indexer: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile
sub-clang-indexer-make_first-ordered: sub-libindexdb-make_first-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-clang-indexer-make_first: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-clang-indexer-all-ordered: sub-libindexdb-all-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-clang-indexer-all: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-clang-indexer-clean-ordered: sub-libindexdb-clean-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-clang-indexer-clean: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-clang-indexer-distclean-ordered: sub-libindexdb-distclean-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-clang-indexer-distclean: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-clang-indexer-install_subtargets-ordered: sub-libindexdb-install_subtargets-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-clang-indexer-install_subtargets: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-clang-indexer-uninstall_subtargets-ordered: sub-libindexdb-uninstall_subtargets-ordered  FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-clang-indexer-uninstall_subtargets: FORCE
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-index-tool-qmake_all: sub-clang-indexer-qmake_all FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
	cd index-tool\ && $(MAKE) -f Makefile qmake_all
sub-index-tool: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile
sub-index-tool-make_first-ordered: sub-clang-indexer-make_first-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-index-tool-make_first: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-index-tool-all-ordered: sub-clang-indexer-all-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-index-tool-all: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-index-tool-clean-ordered: sub-clang-indexer-clean-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-index-tool-clean: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-index-tool-distclean-ordered: sub-clang-indexer-distclean-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-index-tool-distclean: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-index-tool-install_subtargets-ordered: sub-clang-indexer-install_subtargets-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-index-tool-install_subtargets: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-index-tool-uninstall_subtargets-ordered: sub-clang-indexer-uninstall_subtargets-ordered  FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-index-tool-uninstall_subtargets: FORCE
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-navigator-qmake_all: sub-index-tool-qmake_all FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
	cd navigator\ && $(MAKE) -f Makefile qmake_all
sub-navigator: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile
sub-navigator-make_first-ordered: sub-index-tool-make_first-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-navigator-make_first: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile 
sub-navigator-all-ordered: sub-index-tool-all-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-navigator-all: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile all
sub-navigator-clean-ordered: sub-index-tool-clean-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-navigator-clean: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile clean
sub-navigator-distclean-ordered: sub-index-tool-distclean-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-navigator-distclean: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile distclean
sub-navigator-install_subtargets-ordered: sub-index-tool-install_subtargets-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-navigator-install_subtargets: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile install
sub-navigator-uninstall_subtargets-ordered: sub-index-tool-uninstall_subtargets-ordered  FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall
sub-navigator-uninstall_subtargets: FORCE
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile uninstall

Makefile: ../sourceweb-master/sourceweb.pro ../../../../Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf ../../../../Qt/5.8/mingw53_32/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/qdevice.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/device_config.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/common/angle.conf \
		../../../../Qt/5.8/mingw53_32/mkspecs/qconfig.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/qt_config.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/spec_post.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/toolchain.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/default_pre.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../sourceweb-master/config.pri \
		../sourceweb-master/check-clang.pri \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/default_post.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/rtti.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/precompile_header.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/warn_on.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/file_copies.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/windows.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/exceptions.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/yacc.prf \
		../../../../Qt/5.8/mingw53_32/mkspecs/features/lex.prf \
		../sourceweb-master/sourceweb.pro
	$(QMAKE) -o Makefile ..\sourceweb-master\sourceweb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"
../../../../Qt/5.8/mingw53_32/mkspecs/features/spec_pre.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/qdevice.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/features/device_config.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/common/angle.conf:
../../../../Qt/5.8/mingw53_32/mkspecs/qconfig.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/features/qt_functions.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/qt_config.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/spec_post.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/toolchain.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/default_pre.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf:
../sourceweb-master/config.pri:
../sourceweb-master/check-clang.pri:
../../../../Qt/5.8/mingw53_32/mkspecs/features/resolve_config.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/default_post.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/rtti.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/precompile_header.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/warn_on.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/qmake_use.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/file_copies.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/win32/windows.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/exceptions.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/yacc.prf:
../../../../Qt/5.8/mingw53_32/mkspecs/features/lex.prf:
../sourceweb-master/sourceweb.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ..\sourceweb-master\sourceweb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries"

qmake_all: sub-third_party-qmake_all sub-libindexdb-qmake_all sub-clang-indexer-qmake_all sub-index-tool-qmake_all sub-navigator-qmake_all FORCE

make_first: sub-third_party-make_first-ordered sub-libindexdb-make_first-ordered sub-clang-indexer-make_first-ordered sub-index-tool-make_first-ordered sub-navigator-make_first-ordered  FORCE
all: sub-third_party-all-ordered sub-libindexdb-all-ordered sub-clang-indexer-all-ordered sub-index-tool-all-ordered sub-navigator-all-ordered  FORCE
clean: sub-third_party-clean-ordered sub-libindexdb-clean-ordered sub-clang-indexer-clean-ordered sub-index-tool-clean-ordered sub-navigator-clean-ordered  FORCE
distclean: sub-third_party-distclean-ordered sub-libindexdb-distclean-ordered sub-clang-indexer-distclean-ordered sub-index-tool-distclean-ordered sub-navigator-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-third_party-install_subtargets-ordered sub-libindexdb-install_subtargets-ordered sub-clang-indexer-install_subtargets-ordered sub-index-tool-install_subtargets-ordered sub-navigator-install_subtargets-ordered FORCE
uninstall_subtargets: sub-third_party-uninstall_subtargets-ordered sub-libindexdb-uninstall_subtargets-ordered sub-clang-indexer-uninstall_subtargets-ordered sub-index-tool-uninstall_subtargets-ordered sub-navigator-uninstall_subtargets-ordered FORCE

sub-third_party-debug_ordered:
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile debug
sub-libindexdb-debug_ordered: sub-third_party-debug_ordered 
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile debug
sub-clang-indexer-debug_ordered: sub-libindexdb-debug_ordered 
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile debug
sub-index-tool-debug_ordered: sub-clang-indexer-debug_ordered 
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile debug
sub-navigator-debug_ordered: sub-index-tool-debug_ordered 
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile debug
debug: sub-third_party-debug_ordered sub-libindexdb-debug_ordered sub-clang-indexer-debug_ordered sub-index-tool-debug_ordered sub-navigator-debug_ordered

sub-third_party-release_ordered:
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile release
sub-libindexdb-release_ordered: sub-third_party-release_ordered 
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile release
sub-clang-indexer-release_ordered: sub-libindexdb-release_ordered 
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile release
sub-index-tool-release_ordered: sub-clang-indexer-release_ordered 
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile release
sub-navigator-release_ordered: sub-index-tool-release_ordered 
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile release
release: sub-third_party-release_ordered sub-libindexdb-release_ordered sub-clang-indexer-release_ordered sub-index-tool-release_ordered sub-navigator-release_ordered

sub-third_party-check_ordered:
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile check
sub-libindexdb-check_ordered: sub-third_party-check_ordered 
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile check
sub-clang-indexer-check_ordered: sub-libindexdb-check_ordered 
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile check
sub-index-tool-check_ordered: sub-clang-indexer-check_ordered 
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile check
sub-navigator-check_ordered: sub-index-tool-check_ordered 
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile check
check: sub-third_party-check_ordered sub-libindexdb-check_ordered sub-clang-indexer-check_ordered sub-index-tool-check_ordered sub-navigator-check_ordered

sub-third_party-benchmark_ordered:
	@if not exist third_party\ mkdir third_party\ & if not exist third_party\ exit 1
	cd third_party\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\third_party\third_party.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile benchmark
sub-libindexdb-benchmark_ordered: sub-third_party-benchmark_ordered 
	@if not exist libindexdb\ mkdir libindexdb\ & if not exist libindexdb\ exit 1
	cd libindexdb\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\libindexdb\libindexdb.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile benchmark
sub-clang-indexer-benchmark_ordered: sub-libindexdb-benchmark_ordered 
	@if not exist clang-indexer\ mkdir clang-indexer\ & if not exist clang-indexer\ exit 1
	cd clang-indexer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\clang-indexer\clang-indexer.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile benchmark
sub-index-tool-benchmark_ordered: sub-clang-indexer-benchmark_ordered 
	@if not exist index-tool\ mkdir index-tool\ & if not exist index-tool\ exit 1
	cd index-tool\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\index-tool\index-tool.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile benchmark
sub-navigator-benchmark_ordered: sub-index-tool-benchmark_ordered 
	@if not exist navigator\ mkdir navigator\ & if not exist navigator\ exit 1
	cd navigator\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Marko\Desktop\sourceweb-master\navigator\navigator.pro -spec win32-g++ "CLANG_DIR=D:\llvm\mingwLLVMLibraries" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-third_party-benchmark_ordered sub-libindexdb-benchmark_ordered sub-clang-indexer-benchmark_ordered sub-index-tool-benchmark_ordered sub-navigator-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

